service: site-ses

# Use the `serverless-webpack` plugin to transpile ES6.
plugins:
  - serverless-webpack
  - serverless-offline

# `serverless-webpack` configuration
# Enable auto-packing of external modules.
custom:
  environment: ${file(env.yml):${self:provider.stage}}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: ${self:custom.environment.REGION}
  environment: ${self:custom.environment}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  siteMailer:
    handler: handler.siteMailer
    events:
      - http:
          method: post
          path: site-mailer
          cors: true
